config/routes.rb
##
# Routing for PURL
#
# IIIF Routing
# v3 if a client specifically requests v3 via URL or Accept headers
# v2 by default
Rails.application.routes.draw do
  root to: 'purl#index'

  # handle the singe static grandfathered exception (the first druid/PURL we ever issued for publication)
  get '/ir:rs276tc2764', to: redirect('/rs276tc2764')


  # https://jirasul.stanford.edu/jira/browse/SAR-3557
  # This purl was already published on https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2018.00486/full
  get '/qb590gz1324', to: redirect('/cw402ct1499')

  resource :feedback_form, path: 'feedback', only: [:new, :create]
  get 'feedback' => 'feedback_forms#new'

  get ':id/file/:file' => 'purl#file', as: :purl_file
  get ':id/metrics' => 'purl#metrics', as: :purl_metrics


  resources :purl, only: [:show], path: '/' do
    member do
      get 'version/:version', to: 'purl#show', as: :version
      get 'version/:version/iiif3/manifest', to: 'iiif#manifest', format: false, defaults: { iiif_version: 'v3', iiif_scope: 'iiif3' }

      get 'embed', to: redirect("/iframe/?url=#{Settings.embed.url % { druid: '%{id}' }}")
      # These routes should only be used until our viewers support v3 manifests.
      # We should aim to only serve a IIIF resource from a single URL.
      scope :iiif3, as: :iiif3, format: false, defaults: { iiif_version: 'v3', iiif_scope: 'iiif3' } do
        get 'manifest', to: 'iiif#manifest'
        get 'manifest.json', to: redirect('/%{id}/iiif3/manifest'), format: false

        get 'annotation_page/:resource_id' => 'iiif#annotation_page', as: :annotation_page, format: false, defaults: { iiif_version: 'v3' }
        get 'annotation_page/:resource_id.json', to: redirect('/%{id}/iiif3/annotation_page/%{resource_id}'), format: false

        get 'annotations/:resource_id' => 'iiif#annotation_list', as: :annotation_list, format: false, defaults: { iiif_version: 'v3' }
        get 'annotations/:resource_id.json', to: redirect('/%{id}/iiif3/annotations/%{resource_id}'), format: false

        get 'annotation/:resource_id' => 'iiif#annotation', as: :annotation, format: false, defaults: { iiif_version: 'v3' }
        get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif3/annotation/%{resource_id}'), format: false
      end

      scope :iiif, as: :iiif do
        #
        # Sets up the ability to specify an Accept header which should provide a v3
        # manifest. Eventually, v3 should be served by default.
        scope format: true, constraints: AcceptHeaderConstraint.new do
          get 'manifest', to: 'iiif#manifest', format: false, defaults: { iiif_version: 'v3' }
          get 'manifest.json', to: redirect('/%{id}/iiif/manifest'), format: false

          get 'annotation_page/:resource_id' => 'iiif#annotation_page', format: false, defaults: { iiif_version: 'v3' }
          get 'annotation_page/:resource_id.json', to: redirect('/%{id}/iiif/annotation_page/%{resource_id}'), format: false

          get 'annotation/:resource_id' => 'iiif#annotation', format: false, defaults: { iiif_version: 'v3' }
          get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif/annotation/%{resource_id}'), format: false
        end

        get 'manifest', to: 'iiif#manifest', format: false
        get 'manifest.json', to: redirect('/%{id}/iiif/manifest'), format: false

        get 'annotationList/:resource_id' => 'iiif#annotation_list', as: :annotation_list, format: false
        get 'annotationList/:resource_id.json', to: redirect('/%{id}/iiif/annotationList/%{resource_id}'), format: false

        get 'annotation/:resource_id' => 'iiif_#annotation', as: :annotation, format: false
        get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif/annotation/%{resource_id}'), format: false
      end
    end
  end

  options '/:id', to: 'purl#options'

  scope constraints: AcceptHeaderConstraint.new do
    options '/:id/*whatever', to: 'iiif#options', defaults: { iiif_version: 'v3' }
  end

  options '/:id/*whatever', to: 'iiif#options'
end

Rails.application.routes.named_routes.path_helpers_module.module_eval do
  # @param [PurlVersion] a PurlVersion object
  # @return path for the show route
  def purl_version_path(purl_version, options = {})
    version_purl_path(id: purl_version.druid, version: purl_version.version_id)
  end
end

app/views/shared/_brand_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark bg-cardinal">
  <div class="container">
    <a class="mb-0 navbar-brand navbar-logo" href="https://library.stanford.edu" aria-label="Stanford University Libraries"></a>
    <button
      class="navbar-toggler navbar-toggler-right collapsed"
      type="button"
      data-toggle="collapse"
      data-bs-toggle="collapse"
      data-target="#user-util-collapse"
      data-bs-target="#user-util-collapse"
      aria-controls="user-util-collapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="d-md-block d-none">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to '#feedback-form', class: 'nav-link', data: { bs_toggle: 'collapse', bs_target: '#feedback-form' } do %>
            Feedback
          <% end if show_feedback_form? %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="masthead bg-dark bg-cardinal">
  <div class="container">
    <div
      class="d-flex flex-wrap align-items-end pt-3 pb-1 pb-md-3 gap-2"
    >
      <div class="d-flex align-items-end gap-2 flex-grow-1">
        <span class="rosette-logo me-1 align-self-start flex-shrink-0" aria-hidden="true"></span>
        <div class="me-1 flex-grow-1">
          <div class="h1 my-0">
            <a href="/">Stanford Digital Repository</a>
          </div>
        </div>
      </div>
      <div class="navbars ms-md-auto bg-dark">
        <nav
          class="collapse navbar-collapse align-items-start justify-content-md-end navbar-expand-md d-md-flex flex-column flex-md-row"
          aria-label="Browse"
          id="user-util-collapse"
        >
          <ul class="navbar-nav d-md-none gap-0 w-100">
            <li class="nav-item">
              <%= link_to '#feedback-form', class: 'nav-link', data: { bs_toggle: 'collapse', bs_target: '#feedback-form' } do %>
                Feedback
              <% end if show_feedback_form? %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

<% if show_feedback_form? %>
  <div id="feedback-form" class="feedback-form-container collapse">
    <turbo-frame id="feedback-form-frame" src="<%= new_feedback_form_path %>" loading="lazy">
    </turbo-frame>
  </div>
<% end %>

app/views/shared/_su_footer.html.erb
<footer>
  <section id="pre-footer" class="py-4" aria-label="Library footer">
    <div class="container">
      <div class="row row-gap-3">
        <div id="sul-footer-img" class="d-none d-md-flex d-lg-none d-xl-flex col-sm-12 col-lg-3 col-xl-3 d-flex align-items-start justify-content-lg-start justify-content-md-center">
          <a href="https://library.stanford.edu" class="prefooter-logo stacked-lg" aria-label="Stanford University Libraries"></a>
        </div>
        <section class="col-md-4 col-xl-3 primary-menu" aria-label="Main links">
          <div class="d-block d-md-none d-lg-block d-xl-none mb-3">
            <a href="https://library.stanford.edu" class="prefooter-logo" aria-label="Stanford University Libraries"></a>
          </div>
          <ul class="list-unstyled fw-semibold">
            <li>
              <a href="https://library.stanford.edu/all-locations-and-hours">All locations and hours
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
            <li>
              <a href="https://library.stanford.edu/">Library website
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
            <li>
              <a href="https://mylibrary.stanford.edu">My Account
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
          </ul>
        </section>
        <section class="col-md-4 col-xl-3 secondary-menu" aria-labelledby="get-help-header">
          <header id="get-help-header" class="fw-semibold fs-5 mb-2">
                    Get help
          </header>
          <ul class="list-unstyled">
            <li>
              <a href="https://library.stanford.edu/contact-us">Contact us</a>
            </li>
            <li>
              <a href="https://library.stanford.edu/library-accessibility">Library accessibility</a>
            </li>
            <li>
              <a href="https://library-status.stanford.edu/">System status</a>
            </li>
            <li>
              <a href="https://library.stanford.edu/ask/email/connection-problems">Report a connection problem</a>
            </li>
          </ul>
        </section>
        <section class="col-md-4 col-xl-3 secondary-menu" aria-labelledby="search-header">
          <header id="search-header" class="fw-semibold fs-5 mb-2">
                    Search
          </header>
          <ul class="list-unstyled">
            <li>
              <a href="https://searchworks.stanford.edu/">SearchWorks Catalog</a>
                      |
              <a href="https://searchworks.stanford.edu/articles">Articles+</a>
            </li>
            <li>
              <a href="https://archives.stanford.edu/">Archival Collections at Stanford</a>
            </li>
            <li>
              <a href="https://spotlight.stanford.edu/">Spotlight Exhibits</a>
            </li>
            <li>
              <a href="https://earthworks.stanford.edu/">EarthWorks</a>
            </li>
            <li>
              <a href="https://guides.library.stanford.edu/">Guides</a>
            </li>
          </ul>
        </section>
      </div>
    </div>
  </section>
  <section id="su-footer" class="text-white bg-dark pt-4 pb-4" aria-label="Stanford University footer">
    <div class="container-lg d-flex flex-column flex-lg-row align-items-center align-md-normal" title="Common Stanford resources">
      <div class="mt-1 mb-2 align-self-lg-start">
        <a class="su-logo" href="https://www.stanford.edu">Stanford<br>
          <span class="su-logo-university">University</span></a>
      </div>
      <div class="ms-lg-5">
        <nav aria-label="Global footer menu" class="d-flex flex-row gap-4 gap-sm-0 flex-sm-column justify-content-center justify-content-lg-start align-items-start align-items-sm-center align-items-lg-start">
          <ul class="justify-content-center justify-content-lg-start fw-semibold gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu">
                        Stanford Home<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://visit.stanford.edu/plan/">
                        Maps &amp; Directions<span class="visually-hidden">(link is external)</span></a>
            </li>
            <li>
              <a href="https://www.stanford.edu/search/">
                        Search Stanford<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://emergency.stanford.edu">
                        Emergency Info<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
          <ul class="justify-content-center justify-content-lg-start gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu/site/terms/" title="Terms of use for sites">
                        Terms of Use<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/privacy/" title="Privacy and cookie policy">
                        Privacy<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://uit.stanford.edu/security/copyright-infringement" title="Report alleged copyright infringement">
                        Copyright<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://adminguide.stanford.edu/chapter-1/subchapter-5/policy-1-5-4" title="Ownership and use of Stanford trademarks and images">
                        Trademarks<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://studentservices.stanford.edu/more-resources/student-policies/non-academic/non-discrimination" title="Non-discrimination policy">
                        Non-Discrimination<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/accessibility" title="Report web accessibility issues">
                        Accessibility<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
        </nav>
        <div class="text-center text-lg-start copyright">
          <span class="text-nowrap">© Stanford University.</span><span class="text-nowrap">&nbsp; Stanford, California 94305.</span>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_top_navbar.html.erb
<div class="container">
  <a class="su-brand-bar__logo" href="https://www.stanford.edu">Stanford University</a>
</div>