config/routes.rb
##
# Routing for PURL
#
# IIIF Routing
# v3 if a client specifically requests v3 via URL or Accept headers
# v2 by default
Rails.application.routes.draw do
  root to: 'purl#index'

  # handle the singe static grandfathered exception (the first druid/PURL we ever issued for publication)
  get '/ir:rs276tc2764', to: redirect('/rs276tc2764')


  # https://jirasul.stanford.edu/jira/browse/SAR-3557
  # This purl was already published on https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2018.00486/full
  get '/qb590gz1324', to: redirect('/cw402ct1499')

  resource :feedback_form, path: 'feedback', only: [:new, :create]
  get 'feedback' => 'feedback_forms#new'

  get ':id/file/:file' => 'purl#file', as: :purl_file
  get ':id/metrics' => 'purl#metrics', as: :purl_metrics


  resources :purl, only: [:show], path: '/' do
    member do
      get 'version/:version', to: 'purl#show', as: :version
      get 'version/:version/iiif3/manifest', to: 'iiif#manifest', format: false, defaults: { iiif_version: 'v3', iiif_scope: 'iiif3' }

      get 'embed', to: redirect("/iframe/?url=#{Settings.embed.url % { druid: '%{id}' }}")
      # These routes should only be used until our viewers support v3 manifests.
      # We should aim to only serve a IIIF resource from a single URL.
      scope :iiif3, as: :iiif3, format: false, defaults: { iiif_version: 'v3', iiif_scope: 'iiif3' } do
        get 'manifest', to: 'iiif#manifest'
        get 'manifest.json', to: redirect('/%{id}/iiif3/manifest'), format: false

        get 'annotation_page/:resource_id' => 'iiif#annotation_page', as: :annotation_page, format: false, defaults: { iiif_version: 'v3' }
        get 'annotation_page/:resource_id.json', to: redirect('/%{id}/iiif3/annotation_page/%{resource_id}'), format: false

        get 'annotations/:resource_id' => 'iiif#annotation_list', as: :annotation_list, format: false, defaults: { iiif_version: 'v3' }
        get 'annotations/:resource_id.json', to: redirect('/%{id}/iiif3/annotations/%{resource_id}'), format: false

        get 'annotation/:resource_id' => 'iiif#annotation', as: :annotation, format: false, defaults: { iiif_version: 'v3' }
        get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif3/annotation/%{resource_id}'), format: false
      end

      scope :iiif, as: :iiif do
        #
        # Sets up the ability to specify an Accept header which should provide a v3
        # manifest. Eventually, v3 should be served by default.
        scope format: true, constraints: AcceptHeaderConstraint.new do
          get 'manifest', to: 'iiif#manifest', format: false, defaults: { iiif_version: 'v3' }
          get 'manifest.json', to: redirect('/%{id}/iiif/manifest'), format: false

          get 'annotation_page/:resource_id' => 'iiif#annotation_page', format: false, defaults: { iiif_version: 'v3' }
          get 'annotation_page/:resource_id.json', to: redirect('/%{id}/iiif/annotation_page/%{resource_id}'), format: false

          get 'annotation/:resource_id' => 'iiif#annotation', format: false, defaults: { iiif_version: 'v3' }
          get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif/annotation/%{resource_id}'), format: false
        end

        get 'manifest', to: 'iiif#manifest', format: false
        get 'manifest.json', to: redirect('/%{id}/iiif/manifest'), format: false

        get 'annotationList/:resource_id' => 'iiif#annotation_list', as: :annotation_list, format: false
        get 'annotationList/:resource_id.json', to: redirect('/%{id}/iiif/annotationList/%{resource_id}'), format: false

        get 'annotation/:resource_id' => 'iiif_#annotation', as: :annotation, format: false
        get 'annotation/:resource_id.json', to: redirect('/%{id}/iiif/annotation/%{resource_id}'), format: false
      end
    end
  end

  options '/:id', to: 'purl#options'

  scope constraints: AcceptHeaderConstraint.new do
    options '/:id/*whatever', to: 'iiif#options', defaults: { iiif_version: 'v3' }
  end

  options '/:id/*whatever', to: 'iiif#options'
end

Rails.application.routes.named_routes.path_helpers_module.module_eval do
  # @param [PurlVersion] a PurlVersion object
  # @return path for the show route
  def purl_version_path(purl_version, options = {})
    version_purl_path(id: purl_version.druid, version: purl_version.version_id)
  end
end

app/controllers/feedback_forms_controller.rb
# frozen_string_literal: true

class FeedbackFormsController < ApplicationController
  def new; end

  def create
    if verify_recaptcha(action: 'feedback')
      FeedbackMailer.submit_feedback(params, request.remote_ip).deliver_now
      flash[:success] = 'Thank you! Your feedback has been sent.'
    else
      flash[:error] = 'You must pass the reCAPTCHA challenge'
    end

    redirect_to params[:url]
  end
end

app/views/feedback_forms/new.html.erb
<turbo-frame id="feedback-form-frame">
  <div class="row justify-content-md-center">
    <div class="col-sm-6 my-3">
      <%= form_tag feedback_form_path, method: :post, class:"form-horizontal feedback-form", role:"form", data: { turbo: false, controller: 'feedback recaptcha', feedback_target: 'form', action: 'submit->recaptcha#refresh' } do %>
        <div class="row">
          <div class="col-sm-12 px-4 mb-2">
            <div class="alert alert-info" role="alert">
              Reporting from: <span class="reporting-from-field"><%= request.referer %></span>
              <%= hidden_field_tag :url, request.referer, class:"reporting-from-field" %>
            </div>
          </div>
        </div>
        <%= hidden_field_tag :user_agent %>
        <%= hidden_field_tag :viewport %>
        <div class="mx-3">
          <div class="form-group row mb-3">
            <%= label_tag(:message, 'Message', class: "col-sm-3 col-form-label text-end") %>
            <div class="col-sm-9">
              <%= text_area_tag :message, "", rows:"5", class:"form-control", required: true %>
            </div>
          </div>
          <div class="form-group row mb-3">
            <%= label_tag(:name, 'Your name', class: "col-sm-3 col-form-label text-end") %>
            <div class="col-sm-9">
              <%= text_field_tag :name, "", class:"form-control", required: true %>
            </div>
          </div>
          <div class="form-group row mb-3">
            <%= label_tag(:to, 'Your email', class: "col-sm-3 col-form-label text-end") %>
            <div class="col-sm-9">
              <%= email_field_tag :to, "", class:"form-control", required: true %>
            </div>
          </div>
          <div class="form-group row mb-3">
            <div class="offset-sm-3 col-sm-9">
              <%= render RecaptchaComponent.new(action: 'feedback') %>
            </div>
          </div>
          <div class="form-group row">
            <div class="offset-sm-3 col-sm-9">
              <button type="submit" class="btn btn-primary">Send</button>
              <%= button_tag "Cancel", type: 'button', class: 'btn btn-link', data: { bs_toggle: 'collapse', bs_target: '#feedback-form' }, aria: { expanded: false, controls: 'feedback-form' } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</turbo-frame>